
# This is a deploy workflow for connected-sdk

name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  JAVA_VERSION: 11
  JAVA_DISTRIBUTION: 'adopt'
  NODE_VERSION: 14

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, standard]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Use the node version specified in the strategy
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Use the node version specified in the strategy
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      # Install packages
      - name: Install packages
        run: |
          git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/
          npm install
      - name: Print GITHUB_WORKSPACE
        run: echo ${GITHUB_WORKSPACE}

      # Build an optimized production build
      - name: Call the deploy Bash Script
        run:  bash ${GITHUB_WORKSPACE}/deployment/deploy-gha.sh
      - name: S3 sync
        uses: jakejarvis/s3-sync-action@master
        with:
         args: --acl public-read --follow-symlinks --delete
        env:
         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
         SOURCE_DIR: 'dist'      # optional: defaults to entire repository
         DEST_DIR: 'connected-sdk'

      - name: Install branch-github-actions
        uses: actions/checkout@v3
        with:
         repository: BranchMetrics/branch-github-actions
         ref: master
         path: .branch-github-actions
         token: ${{ secrets.BRANCHLET_ACCESS_TOKEN }}
      - name: Create RC branch
        id: create-rc
        uses: ./branch-github-actions/actions/create-rc
        with:
          version: ${{ steps.get-next-version.outputs.result }}

      - name: Print RC branch
        run: echo ${{ steps.get-next-version.outputs.result }}
