name: Deploy QA
on:
  workflow_dispatch:
    inputs:
      branch_name:
          description: 'Enter name of the branch'
          required: true
          default: 'main'

  pull_request:
    types: [closed]
    branches:
      - main
    paths-ignore:
      - docs/**
      - README.md
env:
  BRANCH_NAME: '${{ github.event.inputs.branch_name || github.head_ref || github.ref_name  }}'
  NODE_VERSION: 16
  JAVA_VERSION: 11
  JAVA_DISTRIBUTION: 'adopt'

jobs:
  test-unit:
    name: Unit tests
    runs-on: small
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Setup .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
            dot-npmrc: ${{ secrets.DOT_NPMRC }}

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "Running tests"

  test-lint:
    name: Lint
    runs-on: small
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Setup .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
            dot-npmrc: ${{ secrets.DOT_NPMRC }}

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint tests
        run: npm run lint

  deploy-qa:
    name: Deploy-QA
    needs: [test-unit,test-lint]
    if: ${{ github.ref_name == 'main' && github.event.pull_request.merged == true }}
    runs-on: small
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Install dependencies
        run: npm install

      - name: Call the Build bash script for QA
        id: build
        run:  bash ${GITHUB_WORKSPACE}/deployment/build-qa.sh

      - name: Sync S3 Builds
        id: s3syncbuilds
        if: steps.build.outcome == 'success'
        run: aws s3 sync ./dist s3://branch-builds/connected-sdk/

      - name: Sync S3 CDN
        id: s3synccdn
        if: steps.s3syncbuilds.outcome == 'success'
        run: aws s3 cp ./dist/branch-connected.min.js s3://branch-cdn/branch-connected.min.js

