name: Deploy
on:
  workflow_dispatch:
    inputs:
      branch_name:
          description: 'Name of the branch'
          required: true
          default: 'main'

  pull_request:
    types: [closed]
    branches:
      - main
      - production
      - releases/**
    paths-ignore:
      - docs/**
      - README.md
env:
  BRANCH_NAME: '${{ github.event.inputs.branch_name || github.head_ref || github.ref_name  }}'
  NODE_VERSION: 16
  JAVA_VERSION: 11
  JAVA_DISTRIBUTION: 'adopt'

jobs:
  checkout-install:
    name: Checkout and Install dependencies
    runs-on: small
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
            dot-npmrc: ${{ secrets.DOT_NPMRC }}

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install packages
        run: npm install

  test-unit:
    name: Unit tests
    needs: checkout-install
    runs-on: small
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "Running tests"

  test-lint:
    name: Lint
    needs: checkout-install
    runs-on: small
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint tests
        run: npm run lint
  build:
    name: Build
    needs: [test-lint, test-unit]
    runs-on: small
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Install dependencies
        run: npm install

      - name: Call the deploy Bash Script
        run:  bash ${GITHUB_WORKSPACE}/deployment/deploy-gha.sh

  deploy:
    name: Deploy
    needs: build
    runs-on: small
    steps:
      - name: dummy deploy
        run: echo "Branch name is $BRANCH_NAME"
        
