name: Deploy
on:
  workflow_dispatch:
    inputs:
      branch_name:
          description: 'Name of the branch'
          required: true
          default: 'main'

  pull_request:
    types: [closed]
    branches:
      - main
      - production
      - releases/**
    paths-ignore:
      - docs/**
      - README.md
env:
  BRANCH_NAME: '${{ github.event.inputs.branch_name || github.head_ref || github.ref_name  }}'
  NODE_VERSION: 16
  JAVA_VERSION: 11
  JAVA_DISTRIBUTION: 'adopt'

jobs:
  checkout-install:
    name: Checkout and Install dependencies
    runs-on: small
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3
      
      - name: Setup .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
            dot-npmrc: ${{ secrets.DOT_NPMRC }}

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        run: npm install

  test-unit:
    name: Unit tests
    needs: checkout-install
    runs-on: small
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "Running tests"

  test-lint:
    name: Lint
    needs: checkout-install
    runs-on: small
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint tests
        run: npm run lint
  build:
    name: Build
    needs: [test-lint, test-unit]
    runs-on: small
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Install dependencies
        run: npm install

      - name: Call the Build bash script for QA
        run:  bash ${GITHUB_WORKSPACE}/deployment/build-qa.sh

  deploy-qa:
    name: Deploy-QA
    needs: build
    if: ${{ github.ref_name == 'main' && github.event.pull_request.merged == true }}
    runs-on: small
    steps:
      - name: Set environment variable "commit-message"
        run: echo "commit-message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      - name: Display environment variable "commit-message"
        run: echo "commit-message=${{ env.commit-message }}"
 
      - name: Display head_commit
        run: echo "${{ github.event.head_commit.message }}"

      - name: Display commits of 1
        run: echo "${{ github.event.commits[0].message }}"

  
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Install dependencies
        run: npm install

      - name: Call the Build bash script for QA
        run:  bash ${GITHUB_WORKSPACE}/deployment/build-qa.sh

      - name: S3 list builds
        run: aws s3 ls s3://branch-builds/connected-sdk --recursive

      - name: S3 list cdn
        run: aws s3 ls s3://branch-cdns --recursive

      - name: Sync S3
        run: | 
              aws s3 sync ./dist s3://branch-builds/connected-sdk/
              aws s3 sync ./dist s3://branch-cdns/

  bump-master:
    name: bump-master
    needs: deploy-qa
    runs-on: small
    steps:
      - name: Run bump script
        run: echo "Running bump"

