name: Test Re-usable

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
jobs:
  build:
    runs-on: [small]
    steps:
      - name: Run tests
        run: echo "Branch name is ${{ inputs.config-path }}"
        
      - name: Try to fail
        run: exit 1
