name: demo
on:
  workflow_dispatch:
    inputs:
      branch_name:
          description: 'Name of the branch'
          required: true
          default: 'main'
            
      perform_deploy_qa:
          description: 'Want to deploy to QA'
          required: true
          type: boolean
        
      perform_deploy_prod:
          description: 'Want to deploy to Prod'
          required: true
          type: boolean
        
      version:
          type: choice
          description: Version for Prod release
          options: 
           - major
           - minor
           - patch

  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main
      - production
      - releases/**
    paths-ignore:
      - docs/**
      - README.md
        
env:
  BRANCH_NAME: '${{ github.event.inputs.branch_name || github.head_ref || github.ref_name  }}'
jobs:
  build:
    runs-on: [small]
    steps:
      - name: Run tests
        run: echo "Branch name is $BRANCH_NAME"

      - name: Echo
        run: |
            echo "Version selected is, ${{ github.event.inputs.version }}!"
            echo "- qa ${{ inputs.perform_deploy_qa }}!"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Prepare Node version
        run: echo "NODE_VERSION=$(grep nodejs .tool-versions | cut -f2 -d' ')" >> $GITHUB_ENV

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
  call-workflow-passing-data:
    uses: ./.github/workflows/test-reusable.yml
    with:
      config-path: $BRANCH_NAME
